import 'package:flutter/material.dart';
import 'description_class.dart';

class CourseListB1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        DescriptionClassB1("Present simple or present continuous",
            "assets/img/first_course.png", "/b1/topic1/explain"),
        DescriptionClassB1(
            "Future forms – will, be going to, present continuous",
            "assets/img/second_course.png",
            "/b1/topic2/explain"),
        DescriptionClassB1("Past simple or present perfect?",
            "assets/img/third_course.png", "/b1/topic3/explain"),
        DescriptionClassB1(
            "Present perfect simple and present perfect continuous",
            "assets/img/fourth_course.png",
            "/b1/topic4/explain"),
        DescriptionClassB1("during, for, while", "assets/img/third_course.png",
            "/b1/topic1/explain"),
        DescriptionClassB1("Comparative and superlative adjectives and adverbs",
            "assets/img/third_course.png", "/b1/topic5/explain"),
        DescriptionClassB1("A(n), the, no article",
            "assets/img/third_course.png", "/b1/topic6/explain"),
        DescriptionClassB1("another, other, others, the other, the others",
            "assets/img/third_course.png", "/b1/topic7/explain"),
        DescriptionClassB1("Can, could, be able to – ability and possibility",
            "assets/img/third_course.png", "/b1/topic8/explain"),
        DescriptionClassB1(
            "Have to, must, should – obligation, prohibition, necessity, advice",
            "assets/img/third_course.png",
            "/b1/topic1/explain"),
        DescriptionClassB1("Reflexive pronouns – myself, yourself",
            "assets/img/third_course.png", "/b1/topic9/explain"),
        DescriptionClassB1("-ed/-ing adjectives – adjectives from verbs",
            "assets/img/third_course.png", "/b1/topic1/explain"),
        DescriptionClassB1("Past simple, past continuous, past perfect",
            "assets/img/third_course.png", "/b1/topic10/explain"),
        DescriptionClassB1("Review of all verb tenses B1",
            "assets/img/third_course.png", "/b1/topic11/explain"),
        DescriptionClassB1("usually, used to, be used to, get used to",
            "assets/img/third_course.png", "/b1/topic12/explain"),
        DescriptionClassB1("Passive verb forms", "assets/img/third_course.png",
            "/b1/topic13/explain"),
        DescriptionClassB1("Active and passive voice",
            "assets/img/third_course.png", "/b1/topic14/explain"),
        DescriptionClassB1(
            "Modal verbs of deduction – must, may, might, could, can’t",
            "assets/img/third_course.png",
            "/b1/topic15/explain"),
        DescriptionClassB1("First conditional, future time clauses",
            "assets/img/third_course.png", "/b1/topic16/explain"),
        DescriptionClassB1("Second conditional – unreal situations",
            "assets/img/third_course.png", "/b1/topic17/explain"),
        DescriptionClassB1("First and second conditionals",
            "assets/img/third_course.png", "/b1/topic18/explain"),
        DescriptionClassB1("Third conditional – past unreal situations",
            "assets/img/third_course.png", "/b1/topic19/explain"),
        DescriptionClassB1("Indirect speech – reported speech",
            "assets/img/third_course.png", "/b1/topic20/explain"),
        DescriptionClassB1("Gerund or infinitive – do, to do, doing",
            "assets/img/third_course.png", "/b1/topic21/explain"),
        DescriptionClassB1(
            "much, many, a lot, little, few, some, any, no – quantifiers",
            "assets/img/third_course.png",
            "/b1/topic22/explain"),
        DescriptionClassB1("all, both – quantifiers",
            "assets/img/third_course.png", "/b1/topic23/explain"),
        DescriptionClassB1("both, either, neither – quantifiers",
            "assets/img/third_course.png", "/b1/topic24/explain"),
        DescriptionClassB1("any, no, none – quantifiers",
            "assets/img/third_course.png", "/b1/topic25/explain"),
        DescriptionClassB1("so, such, such a, so much, so many",
            "assets/img/third_course.png", "/b1/topic26/explain"),
        DescriptionClassB1("Defining and non-defining relative clauses",
            "assets/img/third_course.png", "/b1/topic27/explain"),
        DescriptionClassB1("Question tags – aren’t you? don’t you?",
            "assets/img/third_course.png", "/b1/topic28/explain"),
        DescriptionClassB1("Clauses of contrast, purpose and reason",
            "assets/img/third_course.png", "/b1/topic29/explain"),
        DescriptionClassB1("Verb + preposition – dependent prepositions",
            "assets/img/third_course.png", "/b1/topic30/explain"),
        DescriptionClassB1("Adjective + preposition – dependent prepositions",
            "assets/img/third_course.png", "/b1/topic31/explain"),
        DescriptionClassB1("had better … it’s time",
            "assets/img/third_course.png", "/b1/topic32/explain"),
        DescriptionClassB1("For, since, from – What’s the difference?",
            "assets/img/third_course.png", "/b1/topic33/explain"),
        DescriptionClassB1("Compound adjectives with numbers: ‘a two-day trip’",
            "assets/img/third_course.png", "/b1/topic34/explain"),
        DescriptionClassB1("B1 Phrasal verbs 1 – Exercises and explanation",
            "assets/img/third_course.png", "/b1/topic35/explain"),
        DescriptionClassB1("B1 Phrasal verbs 2 – Exercises and explanation",
            "assets/img/third_course.png", "/b1/topic36/explain"),
        DescriptionClassB1("B1 Phrasal verbs 3 – Exercises and explanation",
            "assets/img/third_course.png", "/b1/topic37/explain"),
        Container(
          height: 50,
        ),
      ],
    );
  }
}
